name: CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm i

      - name: Compile plugin
        run: npm run build -w babel-plugin-wallace

      - name: Run tests
        run: npm test -w wallace